server:
  port: 9090

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

zuul:
  routes:
    api-a:
      path: /provider2/**
      serviceId: provider2
