server:
  port: 8080

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/test
    username: root
    password: Admin123!
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapXml/*.xml
  type-aliases-package: com.bes.provider.domain