server:
  port: 8080

spring:
  application:
    name: provider
  datasource:
    url: jdbc:mysql://192.168.1.60:3306/test
    username: root
    password: Admin123!
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.1.60
    port: 6379
    password: redis
    database: 0
    timeout: 60s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-wait:  -1s
        max-active: -1

mybatis:
  mapper-locations: classpath:mapXml/*.xml
  type-aliases-package: com.bes.provider.domain
